name: Run College Drop Bot

on:
  schedule:
    - cron: "0 15 * * *"  # Daily at 11 AM EST
  workflow_dispatch:      # Allows manual trigger

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: pip install requests

      - name: Run College Knowledge Drop bot
        env:
          AI_USER_NAME: ${{ secrets.AI_USER_NAME }}
          AI_USER_EMAIL: ${{ secrets.AI_USER_EMAIL }}
        run: |
          python bot.py
