name: Run College Drop Bot

on:
  schedule:
    - cron: "0 15 * * *"  # runs daily at 11 AM EST (15:00 UTC)
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run bot
        run: python bot.py

