name: Run College Drop Bot

on:
  schedule:
    - cron: "0 15 * * *"  # daily at 11 AM EST
  workflow_dispatch:      # allow manual trigger

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: pip install requests

      - name: Run bot and save output
        env:
          AI_USER_NAME: ${{ secrets.AI_USER_NAME }}
          AI_USER_EMAIL: ${{ secrets.AI_USER_EMAIL }}
        run: |
          python bot.py

           - name: Commit and push newsletter
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          # Only commit if newsletter file exists
          if ls newsletter_*.txt 1> /dev/null 2>&1; then
            git add newsletter_*.txt
            git commit -m "Add College Knowledge Drop for $(date +'%B_%d_%Y')" || echo "No changes to commit"
            git push
          else
            echo "No newsletter files to commit."
          fi

